### ISSUE TITLE
when wgetting the data files, warn the user a long download has started

### ISSUE THREAD

**Issue by zkbt** [TESScience/SPyFFI#25]

**Comment by zkbt** [comment]
It's great that the code now automatically downloads inputs if they're not found on the user's computer. But, without warning it feels like the the first time SPyFFI runs it just hangs forever.

**Comment by xcthulhu** [comment]
We do - it's info level rather than WARNING

https://github.com/TESScience/SPyFFI/blob/master/settings.py#L60

I guess you need to make sure you set `LOG=INFO` to see it.
