### ISSUE TITLE
How does "logging" work? 

### ISSUE THREAD

**Issue by zkbt** [TESScience/SPyFFI#26]
The code used to print text updates of every step of the process to the terminal. I gather this has now been absorbed into a "logger" object that, I would imagine, send this text to a log file. I would imagine this to be ~/.tess/spyffi/SPyFFI.log, but this file stays at 0 bytes for me, even after lots of stuff has happened. 

Is there a simple way to ask the loggers to report text to the terminal?

**Comment by xcthulhu** [comment]
Good catch, I'm getting rid of the dead code that writes that log file.

By default, all logging goes to stderr so it should be visible in the console but not interfere with scripts that need redirect the output from stdout.  You're not seeing this?  What environment are you using?

**Comment by noqsi** [comment]
On Sep 15, 2016, at 9:41 PM, Zach Berta-Thompson notifications@github.com wrote:

> Is there a simple way to ask the loggers to report text to the terminal?

Set LOG=INFO (or whatever level you choose) in your environment.

John Doty              Noqsi Aerospace, Ltd.
http://www.noqsi.com/
jpd@noqsi.com

**Comment by doctormo** [comment]
The best way to provide the feature inside the scripts, is to process args and look for the -v --verbose option, which if set is a good indicator to turn on INFO level logging.

**Comment by sdynes** [comment]
Hello Matt - 

Just want to check if you are OK with getting email from the class about challenges with SPyFFI. 

As this is your repository, you are free to make any changes you'd like. 

I do want to be clear that you'd be doing this on your own time, as TESS is not subsidizing this effort. 

Let me know if you have any questions.


Thanks!

-Scott


-----Original Message-----
